// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// correctCounts
DataFrame correctCounts(DataFrame baseCount, DataFrame multiCount);
RcppExport SEXP correctMultiCount_correctCounts(SEXP baseCountSEXP, SEXP multiCountSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type baseCount(baseCountSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type multiCount(multiCountSEXP);
    __result = Rcpp::wrap(correctCounts(baseCount, multiCount));
    return __result;
END_RCPP
}
